spring:
  main:
    # Kein Banner wegen JSON-Logging
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oauth2.issuer-uri}

oauth2:
  issuer-uri: http://localhost:7070

server:
  port: 7071
  
management:
  health:
    binders:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
