spring:
  main:
    # Kein Banner wegen JSON-Logging
    banner-mode: off
server:
  port: 7070
management:
  health:
    binders:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
