spring:
  main:
    # Kein Banner wegen JSON-Logging
    banner-mode: off
  security:
    oauth2:
      client:
        registration:
          authscs-client-credentials:
            provider: spring
            client-id: authscs
            client-secret: secret
            authorization-grant-type: client_credentials
            client-name: authscs-client-credentials
            scope: authscs.read
        provider:
          spring:
            issuer-uri: ${oauth2.issuer-uri}

oauth2:
  issuer-uri: http://localhost:7070
  server-uri: http://localhost:7071/api

server:
  port: 7072

management:
  health:
    binders:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
