spring:
  main:
    # Kein Banner wegen JSON-Logging
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7070
server:
  port: 7071
management:
  health:
    binders:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
