# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # https://github.com/actions/checkout
    - uses: actions/checkout@v3

    # https://github.com/actions/setup-java
    # https://github.com/actions/cache
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    # https://github.com/gradle/gradle
    - run: chmod +x gradlew 
    - run: ./gradlew build --parallel
    - run: ./gradlew dockerBuild

    # https://github.com/features/packages
    - if: startsWith(github.ref, 'refs/tags')
      name: Update Packages (tag)
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        API=`echo "ghcr.io/${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
        TAG=`cat VERSION`
        NAME=authscs/auth-server
        docker tag $NAME:$TAG $API/$NAME:$TAG
        docker push $API/$NAME:$TAG
        NAME=authscs/demo-server
        docker tag $NAME:$TAG $API/$NAME:$TAG
        docker push $API/$NAME:$TAG
        NAME=authscs/demo-client
        docker tag $NAME:$TAG $API/$NAME:$TAG
        docker push $API/$NAME:$TAG
